# Config file for Air hot-reload
[build]
cmd = "go build -o ./bin/server ./cmd/server"
bin = "server"
full_bin = "./bin/server"
watch_dir = "."
exclude_dir = ["db", "vendor", "templates"]
delve = false
log = "air_errors.log"
